Modification du script run_full_workflow.py pour télécharger un audio en fonction du jour et créer l'audio et les timecodes en fonction des chroniques non scrapées
Quand je lance :
python3 train_camembert.py

J'ai :
Chargement des données...
Dossiers de début trouvés : 198
Dossiers de fin trouvés : 198
Total d'échantillons : 4920
Distribution des labels :
label
1    2481
0    2439
Name: count, dtype: int64
Initialisation du tokenizer camembert-base...
Chargement du modèle camembert-base...
Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 197/197 [00:00<00:00, 6569.96it/s]
[transformers] CamembertForSequenceClassification LOAD REPORT from: camembert-base
Key                         | Status     | Details
----------------------------+------------+--------
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
classifier.dense.weight     | MISSING    |
classifier.out_proj.bias    | MISSING    |
classifier.out_proj.weight  | MISSING    |
classifier.dense.bias       | MISSING    |

Notes:
- UNEXPECTED:   can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:      those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Entrainement sur : mps
Traceback (most recent call last):
  File "/Users/eglantine/Dev/0.perso/2.Proutechos/9.GroovyMorning/4.rd/1.IAChronicleDetector/0.IAChronicleDetection/6.LiveTranscriptionStartAndEndDetection/train_camembert.py", line 191, in <module>
    train()
  File "/Users/eglantine/Dev/0.perso/2.Proutechos/9.GroovyMorning/4.rd/1.IAChronicleDetector/0.IAChronicleDetection/6.LiveTranscriptionStartAndEndDetection/train_camembert.py", line 137, in train
    training_args = TrainingArguments(
                    ^^^^^^^^^^^^^^^^^^
TypeError: TrainingArguments.__init__() got an unexpected keyword argument 'use_mps_device'

---